'use client';
import { useState, useRef } from 'react';
import { motion, AnimatePresence } from 'framer-motion';
import { X, FileText, Calendar, Share2, CheckCircle } from 'lucide-react';

const WARM_BORDER = '1px solid rgba(180,155,120,0.22)';
const CREAM = '#FDFCF8';

interface Measure {
  measure_id: string;
  title: string;
  summary: string;
  category: string;
  personal_annual_usd: number;
}

interface Props {
  measures: Measure[];
}

// ── ICS generator ─────────────────────────────────────────────────────────────
function buildICS(measures: Measure[]): string {
  const electionDay = '20241105';
  const lines = measures.map(m => `  - ${m.title}: ${m.summary?.slice(0, 80) ?? ''}`).join('\n');
  const notes = `Your Candid ballot summary:\\n\\n${lines}\\n\\nGenerated by Candid.`;
  return [
    'BEGIN:VCALENDAR',
    'VERSION:2.0',
    'PRODID:-//Candid//BallotExport//EN',
    'BEGIN:VEVENT',
    `UID:candid-election-${Date.now()}@candid`,
    `DTSTART;VALUE=DATE:${electionDay}`,
    `DTEND;VALUE=DATE:${electionDay}`,
    'SUMMARY:Election Day - Your Candid Ballot is Ready',
    `DESCRIPTION:${notes}`,
    'BEGIN:VALARM',
    'TRIGGER:-PT120M',
    'ACTION:DISPLAY',
    'DESCRIPTION:Time to vote! Your Candid ballot summary is in these notes.',
    'END:VALARM',
    'END:VEVENT',
    'END:VCALENDAR',
  ].join('\r\n');
}

// ── PDF generator ─────────────────────────────────────────────────────────────
async function exportPDF(measures: Measure[]) {
  const { jsPDF } = await import('jspdf');
  const doc = new jsPDF({ orientation: 'portrait', unit: 'mm', format: 'a4' });

  const W = 210, margin = 16, colW = W - margin * 2;
  const pageH = 297;

  // ── Header band ──────────────────────────────────────────────────────────
  doc.setFillColor(28, 25, 23);
  doc.rect(0, 0, W, 28, 'F');
  doc.setTextColor(253, 252, 248);
  doc.setFontSize(16);
  doc.setFont('helvetica', 'bold');
  doc.text('candid.', margin, 17);
  doc.setFontSize(9);
  doc.setFont('helvetica', 'normal');
  doc.setTextColor(168, 160, 154);
  doc.text('Your Ballot Cheat Sheet — bring this to the polls', margin + 30, 17);

  // ── Page title ────────────────────────────────────────────────────────────
  doc.setTextColor(28, 25, 23);
  doc.setFontSize(22);
  doc.setFont('helvetica', 'bold');
  doc.text('Ballot Summary', margin, 46);

  doc.setFontSize(10);
  doc.setFont('helvetica', 'normal');
  doc.setTextColor(120, 113, 108);
  doc.text(
    `${measures.length} measure${measures.length !== 1 ? 's' : ''} · Generated ${new Date().toLocaleDateString('en-US', { month: 'long', day: 'numeric', year: 'numeric' })}`,
    margin, 54
  );

  // Divider
  doc.setDrawColor(220, 210, 195);
  doc.setLineWidth(0.4);
  doc.line(margin, 59, W - margin, 59);

  // ── Instruction row ────────────────────────────────────────────────────────
  doc.setFontSize(8);
  doc.setFont('helvetica', 'italic');
  doc.setTextColor(160, 150, 140);
  doc.text('For each measure: read the summary, check your impact, then circle YES or NO at the booth.', margin, 65);

  let y = 74;

  const CATEGORY_EMOJI: Record<string, string> = {
    housing: 'Housing',
    education: 'Education',
    environment: 'Environment',
    public_safety: 'Public Safety',
    transportation: 'Transportation',
    healthcare: 'Healthcare',
    economy: 'Economy',
    jobs: 'Jobs & Economy',
    other: 'Other',
  };

  for (let i = 0; i < measures.length; i++) {
    const m = measures[i];
    const summary = m.summary ?? 'No summary available.';
    const cat = CATEGORY_EMOJI[m.category] ?? m.category.replace(/_/g, ' ');

    const titleLines   = doc.splitTextToSize(m.title, colW - 20);
    const summaryLines = doc.splitTextToSize(summary, colW - 20);

    const impact     = isFinite(+m.personal_annual_usd) ? +m.personal_annual_usd : 0;
    const absImpact  = Math.abs(impact);
    const impactStr  = absImpact === 0
      ? 'No direct cost'
      : `${impact < 0 ? 'Saves' : 'Costs'} ~$${absImpact >= 1000 ? (absImpact / 1000).toFixed(1) + 'k' : absImpact.toFixed(0)}/yr`;

    // Card height: top padding + title + gap + summary + impact row + bottom padding
    const cardH = 8 + titleLines.length * 6.5 + 5 + summaryLines.length * 5.2 + 12 + 8;

    if (y + cardH > pageH - 20) {
      doc.addPage();
      y = 20;
    }

    // Card background
    doc.setFillColor(i % 2 === 0 ? 253 : 248, i % 2 === 0 ? 252 : 249, i % 2 === 0 ? 248 : 244);
    doc.setDrawColor(210, 195, 175);
    doc.setLineWidth(0.25);
    doc.roundedRect(margin, y, colW, cardH, 4, 4, 'FD');

    // Measure number badge
    doc.setFillColor(28, 25, 23);
    doc.roundedRect(margin + 5, y + 7, 8, 8, 2, 2, 'F');
    doc.setTextColor(253, 252, 248);
    doc.setFontSize(7);
    doc.setFont('helvetica', 'bold');
    doc.text(String(i + 1), margin + 6.8, y + 13, { align: 'center' });

    // Category pill
    doc.setFontSize(7);
    doc.setFont('helvetica', 'bold');
    doc.setTextColor(100, 90, 80);
    doc.text(cat.toUpperCase(), margin + 17, y + 12);

    // Title
    doc.setFontSize(11);
    doc.setFont('helvetica', 'bold');
    doc.setTextColor(28, 25, 23);
    doc.text(titleLines, margin + 6, y + 20);

    const afterTitle = y + 20 + titleLines.length * 6.5 + 3;

    // Summary
    doc.setFontSize(9);
    doc.setFont('helvetica', 'normal');
    doc.setTextColor(70, 65, 60);
    doc.text(summaryLines, margin + 6, afterTitle);

    const afterSummary = afterTitle + summaryLines.length * 5.2 + 4;

    // Divider before bottom row
    doc.setDrawColor(220, 210, 195);
    doc.setLineWidth(0.2);
    doc.line(margin + 5, afterSummary, margin + colW - 5, afterSummary);

    // Impact label
    doc.setFontSize(8.5);
    doc.setFont('helvetica', 'bold');
    doc.setTextColor(impact < 0 ? 21 : impact > 0 ? 180 : 120, impact < 0 ? 128 : impact > 0 ? 50 : 113, impact < 0 ? 61 : impact > 0 ? 20 : 108);
    doc.text(impactStr, margin + 6, afterSummary + 7);

    // YES / NO checkboxes on the right
    const boxY = afterSummary + 2;
    const boxRight = margin + colW - 8;

    // NO box
    doc.setDrawColor(180, 60, 60);
    doc.setLineWidth(0.5);
    doc.roundedRect(boxRight - 14, boxY, 14, 8, 1.5, 1.5, 'S');
    doc.setFontSize(8);
    doc.setFont('helvetica', 'bold');
    doc.setTextColor(180, 60, 60);
    doc.text('NO', boxRight - 7, boxY + 5.5, { align: 'center' });

    // YES box
    doc.setDrawColor(21, 128, 61);
    doc.roundedRect(boxRight - 30, boxY, 14, 8, 1.5, 1.5, 'S');
    doc.setTextColor(21, 128, 61);
    doc.text('YES', boxRight - 23, boxY + 5.5, { align: 'center' });

    y += cardH + 5;
  }

  // ── Footer ─────────────────────────────────────────────────────────────────
  const totalPages = (doc as any).internal.getNumberOfPages();
  for (let p = 1; p <= totalPages; p++) {
    doc.setPage(p);
    doc.setFontSize(7.5);
    doc.setTextColor(168, 160, 154);
    doc.text('Generated by Candid · candid.vote', margin, pageH - 8);
    doc.text(`Page ${p} of ${totalPages}`, W - margin, pageH - 8, { align: 'right' });
  }

  doc.save('my-ballot-candid.pdf');
}

// ── ICS download ──────────────────────────────────────────────────────────────
function exportICS(measures: Measure[]) {
  const ics = buildICS(measures);
  const blob = new Blob([ics], { type: 'text/calendar;charset=utf-8' });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = 'election-day-candid.ics';
  a.click();
  URL.revokeObjectURL(url);
}

// ── Social card ───────────────────────────────────────────────────────────────
async function exportSocialCard(measures: Measure[], cardRef: HTMLDivElement) {
  const html2canvas = (await import('html2canvas')).default;
  const canvas = await html2canvas(cardRef, { scale: 2, useCORS: true, backgroundColor: '#1C1917' });
  const link = document.createElement('a');
  link.download = 'im-a-prepared-voter.png';
  link.href = canvas.toDataURL('image/png');
  link.click();
}

// ── Social card DOM (rendered off-screen for capture) ─────────────────────────
function SocialCard({ measures, cardRef }: { measures: Measure[]; cardRef: React.Ref<HTMLDivElement> }) {
  const pct = Math.round((measures.length / Math.max(measures.length, 10)) * 100);
  return (
    <div
      ref={cardRef}
      style={{
        position: 'fixed', left: -9999, top: 0,
        width: 480, height: 480,
        background: '#1C1917',
        display: 'flex', flexDirection: 'column',
        alignItems: 'center', justifyContent: 'center',
        padding: 48, fontFamily: 'Georgia, serif',
      }}
    >
      <p style={{ fontSize: 11, fontWeight: 700, letterSpacing: '0.22em', textTransform: 'uppercase', color: 'rgba(253,252,248,0.45)', marginBottom: 20 }}>
        CANDID · CIVIC RESEARCH
      </p>
      <p style={{ fontSize: 42, fontWeight: 800, color: '#FDFCF8', lineHeight: 1.1, textAlign: 'center', marginBottom: 12 }}>
        I&apos;m a Prepared Voter
      </p>
      <p style={{ fontSize: 14, color: 'rgba(253,252,248,0.55)', marginBottom: 36, textAlign: 'center' }}>
        Reviewed {measures.length} measure{measures.length !== 1 ? 's' : ''} before heading to the polls
      </p>
      <div style={{ display: 'flex', gap: 24, marginBottom: 32 }}>
        <div style={{ textAlign: 'center' }}>
          <p style={{ fontSize: 36, fontWeight: 800, color: '#FDFCF8' }}>{measures.length}</p>
          <p style={{ fontSize: 10, color: 'rgba(253,252,248,0.45)', letterSpacing: '0.1em', textTransform: 'uppercase' }}>Measures</p>
        </div>
        <div style={{ width: 1, background: 'rgba(253,252,248,0.12)' }} />
        <div style={{ textAlign: 'center' }}>
          <p style={{ fontSize: 36, fontWeight: 800, color: '#FDFCF8' }}>{pct}%</p>
          <p style={{ fontSize: 10, color: 'rgba(253,252,248,0.45)', letterSpacing: '0.1em', textTransform: 'uppercase' }}>Complete</p>
        </div>
      </div>
      <p style={{ fontSize: 11, color: 'rgba(253,252,248,0.3)', letterSpacing: '0.06em' }}>candid.vote</p>
    </div>
  );
}

// ── Modal ─────────────────────────────────────────────────────────────────────
function ExportModal({ measures, onClose }: { measures: Measure[]; onClose: () => void }) {
  const [loading, setLoading] = useState<string | null>(null);
  const [done, setDone]       = useState<string | null>(null);
  const cardRef = useRef<HTMLDivElement>(null);

  async function run(key: string, fn: () => Promise<void> | void) {
    setLoading(key);
    try { await fn(); setDone(key); setTimeout(() => setDone(null), 2000); }
    finally { setLoading(null); }
  }

  const actions = [
    {
      key: 'pdf',
      icon: <FileText size={22} />,
      label: 'Cheat Sheet PDF',
      sub: 'One page. Every measure. Plain English.',
      fn: () => exportPDF(measures),
    },
    {
      key: 'ics',
      icon: <Calendar size={22} />,
      label: 'Calendar Reminder',
      sub: 'Adds Election Day + your notes to your calendar.',
      fn: () => exportICS(measures),
    },
    {
      key: 'card',
      icon: <Share2 size={22} />,
      label: 'Share Card',
      sub: '"I\'m a Prepared Voter" — no votes shown.',
      fn: () => cardRef.current ? exportSocialCard(measures, cardRef.current) : Promise.resolve(),
    },
  ];

  return (
    <>
      <SocialCard measures={measures} cardRef={cardRef} />

      {/* Backdrop */}
      <motion.div
        initial={{ opacity: 0 }} animate={{ opacity: 1 }} exit={{ opacity: 0 }}
        onClick={onClose}
        style={{ position: 'fixed', inset: 0, background: 'rgba(28,25,23,0.55)', zIndex: 50, backdropFilter: 'blur(4px)' }}
      />

      {/* Modal */}
      <motion.div
        initial={{ opacity: 0, scale: 0.88, y: 24 }}
        animate={{ opacity: 1, scale: 1, y: 0 }}
        exit={{ opacity: 0, scale: 0.92, y: 12 }}
        transition={{ type: 'spring', stiffness: 340, damping: 28 }}
        style={{
          position: 'fixed', left: '50%', top: '50%',
          transform: 'translate(-50%, -50%)',
          width: 'min(480px, calc(100vw - 32px))',
          background: CREAM, border: WARM_BORDER,
          borderRadius: 28, boxShadow: '0 32px 80px rgba(0,0,0,0.18)',
          zIndex: 51, overflow: 'hidden',
        }}
      >
        {/* Header */}
        <div style={{ padding: '24px 24px 0', display: 'flex', alignItems: 'flex-start', justifyContent: 'space-between' }}>
          <div>
            <p style={{ fontSize: 10, fontWeight: 700, letterSpacing: '0.16em', textTransform: 'uppercase', color: '#A8A09A', marginBottom: 4 }}>
              Finalize
            </p>
            <h2 style={{ fontSize: 20, fontWeight: 800, color: '#1C1917', lineHeight: 1 }}>Export your research</h2>
            <p style={{ fontSize: 12, color: '#78716C', marginTop: 4 }}>{measures.length} measure{measures.length !== 1 ? 's' : ''} reviewed</p>
          </div>
          <button onClick={onClose} style={{ background: 'none', border: 'none', cursor: 'pointer', color: '#A8A09A', padding: 4 }}>
            <X size={18} />
          </button>
        </div>

        {/* Actions */}
        <div style={{ padding: '20px 24px 28px', display: 'flex', flexDirection: 'column', gap: 10 }}>
          {actions.map(a => {
            const isLoading = loading === a.key;
            const isDone    = done === a.key;
            return (
              <motion.button
                key={a.key}
                onClick={() => run(a.key, a.fn)}
                whileHover={{ scale: 1.015 }} whileTap={{ scale: 0.98 }}
                disabled={!!loading}
                style={{
                  display: 'flex', alignItems: 'center', gap: 16,
                  padding: '16px 18px', borderRadius: 16,
                  background: isDone ? 'rgba(21,128,61,0.07)' : '#fff',
                  border: isDone ? '1px solid rgba(21,128,61,0.25)' : WARM_BORDER,
                  boxShadow: '0 2px 8px rgba(60,40,20,0.05)',
                  cursor: loading ? 'default' : 'pointer',
                  opacity: loading && !isLoading ? 0.5 : 1,
                  textAlign: 'left',
                }}
              >
                <div style={{ width: 44, height: 44, borderRadius: 12, background: isDone ? 'rgba(21,128,61,0.10)' : 'rgba(180,155,120,0.10)', display: 'flex', alignItems: 'center', justifyContent: 'center', flexShrink: 0, color: isDone ? '#15803D' : '#78716C' }}>
                  {isDone ? <CheckCircle size={22} /> : isLoading
                    ? <motion.div animate={{ rotate: 360 }} transition={{ duration: 0.8, repeat: Infinity, ease: 'linear' }} style={{ width: 20, height: 20, border: '2px solid rgba(180,155,120,0.3)', borderTopColor: '#78716C', borderRadius: '50%' }} />
                    : a.icon}
                </div>
                <div style={{ flex: 1, minWidth: 0 }}>
                  <p style={{ fontSize: 14, fontWeight: 700, color: isDone ? '#15803D' : '#1C1917', marginBottom: 2 }}>
                    {isDone ? 'Done!' : a.label}
                  </p>
                  <p style={{ fontSize: 11.5, color: '#78716C' }}>{a.sub}</p>
                </div>
              </motion.button>
            );
          })}
        </div>
      </motion.div>
    </>
  );
}

// ── FAB + hub ──────────────────────────────────────────────────────────────────
export default function BallotExportHub({ measures }: Props) {
  const [open, setOpen] = useState(false);
  if (!measures.length) return null;

  return (
    <>
      {/* FAB */}
      <motion.button
        onClick={() => setOpen(true)}
        initial={{ scale: 0, opacity: 0 }}
        animate={{ scale: 1, opacity: 1 }}
        transition={{ type: 'spring', stiffness: 300, damping: 22, delay: 0.4 }}
        whileHover={{ scale: 1.06 }} whileTap={{ scale: 0.95 }}
        style={{
          position: 'fixed', bottom: 88, right: 20, zIndex: 40,
          display: 'flex', alignItems: 'center', gap: 8,
          padding: '12px 20px', borderRadius: 99,
          background: '#1C1917', color: '#FDFCF8',
          border: 'none', cursor: 'pointer',
          fontSize: 13, fontWeight: 700,
          boxShadow: '0 8px 28px rgba(28,25,23,0.28)',
        }}
      >
        <FileText size={15} />
        Finalize &amp; Export
      </motion.button>

      {/* Modal */}
      <AnimatePresence>
        {open && <ExportModal measures={measures} onClose={() => setOpen(false)} />}
      </AnimatePresence>
    </>
  );
}
